### ISSUE TITLE
Birthday bot doesn't send greetings to the channel

### ISSUE THREAD

**Issue by nellavasquezp** [NoiTheCat/BirthdayBot#10]
I'm done setting up the bot and configuring the roles, channel, and message but it does not send birthday greetings to the designated channel. How to fix this?

**Comment by MitziMS13** [comment]
A few things to check...

I always start with making sure the bot has the correct permissions in the channel you want it to post the announcement in.  It should have:  Read messages, Send Messages, Embed Links.  Or, you could just give the bot the Administrator permission in your server settings to override all channel permissions.

Next, did it give the birthday person the custom happy birthday role?  If so, manually remove that role from that person and wait a few seconds to see if the bot re-adds it.  If it didn't, check your server settings to make sure the Birthday Bot role is *above the custom happy birthday role.

Then it adds (or re-adds) the role to the person but still doesn't announce, post this to check for possible errors:  bb.test
