### ISSUE TITLE
There's a minor issue with this line, it says next 21 days but it should say 14 to save confusion 

### ISSUE THREAD

**Issue by Kelztergit** [NoiTheCat/BirthdayBot#16]
https://github.com/NoiTheCat/BirthdayBot/blob/4325fdacf23145872699fc204d99bec2295d2742/UserInterface/ListingCommands.cs#L195

Since the thing covers 7 days prior, current day and 14 days into the future it's very confusing if bb.upcoming outputs "There are no recent or upcoming birthdays (within the last 7 days and/or next 21 days)."

I propose it to be Replaced with "There are no recorded birthdays within the last 7 days or the next 14"   or something similar.

**Comment by Kelztergit** [comment]
https://github.com/NoiTheCat/BirthdayBot/blob/4325fdacf23145872699fc204d99bec2295d2742/UserInterface/ListingCommands.cs#L155

Compare with

**Comment by NoiTheCat** [comment]
You're completely right, it's meant to say 14 instead of 21. That whole thing deserves a rewrite anyway, but I've got other priorities at the moment...
Thank you very much for pointing it out! I'll get it fixed up shortly.
