### ISSUE TITLE
Time zone does not persist when re-setting birthday

### ISSUE THREAD

**Issue by EmberHeartshine** [NoiTheCat/BirthdayBot#26]
Steps to reproduce:

1. Set birthday
2. Set TZ
3. Set birthday again
4. Observe that TZ is forgotten

**Comment by NoiTheCat** [comment]
Hello, thank you for the report!

Looks like this is due to a small, subtle oversight in how the command is handled. I believe I've found the issue and it'll be updated in the main bot very soon.
