### ISSUE TITLE
How does one remove the bot?

### ISSUE THREAD

**Issue by igordonin-pareto** [NoiTheCat/BirthdayBot#3]
I kicked the bot out of the server and now I can't remove the Role it created.

**Comment by spinfish** [comment]
Is it managed by an integration by any chance?

**Comment by NoiTheCat** [comment]
Hello, and apologies for the delay. I hadn't heard of others having a similar issue before. If this is still a problem for you, I encourage you to ask in the support server so we could try and take a better look, as well as respond much more quickly.
