### ISSUE TITLE
Upcoming glitch?

### ISSUE THREAD

**Issue by jewel60** [NoiTheCat/BirthdayBot#5]
Hello i have birthday bot in my server and for about a week now it has sad there is no recent upcoming birthdays when I know there is. Is there a way to fix this? I also tried getting on the discord y’all have for help but the link wouldn’t work for me.

**Comment by NoiTheCat** [comment]
Hello! Sorry for the very late response - I would have normally recommended that you join the support server for a much faster reply but it's odd that you weren't able to join it.

As for the bug, would it be related to #16? There was an issue for a while about the command saying it searched for a wider range of dates than it actually looked through. If the upcoming birthdays were more than *two* weeks off, they would not show up as opposed to longer than that.
