### ISSUE TITLE
not working anymore

### ISSUE THREAD

**Issue by marvin783** [NoiTheCat/BirthdayBot#7]
The Bot is not working anymore on different Discord Servers. Can you fix that?

**Comment by NoiTheCat** [comment]
These issues are usually fixed within at most a few hours of them happening, and are also not the sorts of issues to discuss here. Please open an issue if you find that the bot is working incorrectly. If it's not responding at all or is disconnected, instead reach out on the support server (https://discord.gg/JCRyFk7).
