### ISSUE TITLE
Petit problème avec le bot..

### ISSUE THREAD

**Issue by Myiuu** [NoiTheCat/BirthdayBot#8]
Bonjour / Bonsoir, ce n'est rien de grave mais cela reste dérangeant, le bot ne prend en compte que mes commandes (je suis la fondatrice du serv), pas celles des membres du serveur, (je parle bien de la commande bb.set) j'ai cherché comment pouvoir changé cela mais je n'ai rien trouvé. Pouvez vous m'aidez s'il vous plait, à régler ce petit soucis ? merci :^

**Comment by NoiTheCat** [comment]
Hello! Please excuse my response in English. I don't know French and prefer to not use a translator to assist with my reply. For issues like these, you are welcome to join my server (https://discord.gg/JCRyFk7) to request assistance for this issue. Me or another helper in there would be able to assist you in a more direct way to solve this problem. Thank you!
