### ISSUE TITLE
Repeated message

### ISSUE THREAD

**Issue by puddytawt** [NoiTheCat/BirthdayBot#9]
The birthdaybot keeps resending a birthday announcement every hour, it previously did not do this, how to fix?

**Comment by MitziMS13** [comment]
We’ve seen this happen a lot. There is another bot removing the custom Happy Birthday role from your birthday person.  When this happens, the Birthday Bot is triggered to re-add the role and re-announce.  Check the audit logs for your server to find out who/what is removing the role.
